disabled_rules:
  - line_length
  - todo

opt_in_rules:
  - empty_count
  - first_where
  - sorted_first_last
  - sorted_imports
  - switch_case_alignment
  - vertical_parameter_alignment_on_call
  - yoda_condition
  - shorthand_operator
  - unused_closure_parameter
  - unused_setter_value
  - unneeded_override
  - empty_string
  - fatal_error_message
  - duplicate_imports
  - contains_over_first_not_nil
  - discouraged_optional_collection
  - redundant_discardable_let
  - trailing_closure

excluded:
  - Carthage
  - Pods
  - .build
  - DerivedData

analyzer_rules:
  - explicit_self

force_cast: error
force_try: error

function_body_length: 300
cyclomatic_complexity: 20
file_length: 1000
type_body_length: 500

reporter: "xcode"
